# Generated by Django 5.2.8 on 2025-11-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('qualification', models.JSONField(null=True)),
                ('education', models.CharField(blank=True, choices=[('bsc', 'B.Sc'), ('ba', 'B.A'), ('btech', 'B.Tech'), ('msc', 'M.Sc'), ('ma', 'M.A'), ('mtech', 'M.Tech'), ('mba', 'MBA'), ('phd', 'PhD')], max_length=10, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
                ('document', models.FileField(blank=True, null=True, upload_to='uploads/docs/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='uploads/audios/')),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/videos/')),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
